test:
  config:
    home1: hello this is database-config


#logging.path=logs
#数据源配置
database:
  base:
    url: 172.16.199.18:3306/bs_business
spring:
  datasource:
    #url: jdbc:mysql://${database.base.url}?useunicode=true&characterEncoding=utf8
    url: jdbc:mysql://${database.base.url}?useunicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: mysql
    password: mysql_K9Z9
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 30
      min-idle: 5
    # 配置获取连接等待超时的时间
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#      max-open-prepared-statements:  #和上面的等价
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      #      max-evictable-idle-time-millis:
      filters: stat,wall,log4j
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name:
        principal-cookie-name:
        profile-enable: true
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
      # 配置StatFilter
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # 配置WallFilter
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: false
# 合并多个DruidDataSource的监控数据
#useGlobalDataSourceStat: true

#mybatis.typeAliasesPackage= com.nldc.auth.agency.domain
#mybatis.type-handlers-package=com.nldc.repository.mybatix.handle


query_user: http://id-userinfo/selectuserinfoall
get_oauth2_openid: http://dc-agency/user
#query_user: http://172.16.199.8:9006/selectuserinfoall
#get_oauth2_openid: http://172.16.199.13:7097/apply/auth/user
call_human_society_network_bindCard: http://172.16.199.2:8290/requestIn/AM/humanSociety/bindCard
call_human_society_network_removeRelation: http://172.16.199.2:8290/requestIn/AM/humanSociety/unBindCard
call_human_society_network_refreshCard: http://172.16.199.2:8290/requestIn/AM/humanSociety/updateCard
msgCenterUrl: http://dc-msgin/pushMsg
#msgCenterUrl: http://172.16.199.14:9028/pushMsg

appId: 7546b437367b42d0b1ceb7035fa42dc1
get_oauth2_userid: http://dc-agency/open-id
ip_and_port: http://172.16.199.14:7077_ceshi
